import type { IndustryKey } from '../model';

/**
 * Labels for collection detail "key facts" (virtual detail pages + enhancement sections).
 * Keys are top-level `item.data` roots read by `collectionFacts` in preview-route.
 */
export const COLLECTION_FACT_DETAIL_LABELS: Record<string, string> = {
  category: 'Kategorie',
  price: 'Preis',
  priceFrom: 'Preis ab',
  duration: 'Dauer',
  capacity: 'Kapazitaet',
  scheduleInfo: 'Ablauf',
  sizeSqm: 'Groesse',
  occupancy: 'Belegung',
  bedType: 'Bett',
  view: 'Ausblick',
  travelPeriod: 'Zeitraum',
  distance: 'Distanz',
  elevationGain: 'Hoehenmeter',
  difficulty: 'Level',
  season: 'Saison',
  meetingPoint: 'Treffpunkt',
  preparation: 'Vorbereitung',
  aftercare: 'Danach',
  problemStatement: 'Ausgangslage',
  solutionSummary: 'Loesung',
  serviceArea: 'Region',
  location: 'Ort',
  projectType: 'Projekt',
  targetAudience: 'Zielgruppe',
  coveredByInsurance: 'Abrechnung',
  role: 'Rolle',
  weekday: 'Tag',
  time: 'Uhrzeit',
  level: 'Level',
  trainer: 'Trainer:in',
  guestNote: 'Gaestehinweis',
  bookingHint: 'Buchung',
  ingredients: 'Zutaten',
  allergens: 'Allergene',
  dietaryTags: 'Tags',
  pairingRecommendation: 'Pairing',
  included: 'Inklusive',
  amenities: 'Ausstattung',
  indications: 'Indikationen',
  procedure: 'Ablauf',
  languages: 'Sprachen',
  consultationHours: 'Sprechzeiten',
  certifications: 'Zertifikate',
  equipmentNeeded: 'Equipment',
  goals: 'Fokus',
  mapsUrl: 'Kartenlink',
  problemTypes: 'Problemfelder',
  deliverables: 'Deliverables',
  challenge: 'Ausgangslage',
  industry: 'Branche',
  styleTags: 'Style-Tags',
  relatedServices: 'Passende Leistungen',
  customerQuote: 'Kundenstimme',
  servicesIncluded: 'Leistungen',
  detail: 'Detailzeile',
  metric: 'Kennzahl',
  kicker: 'Kicker',
  author: 'Autor:in',
  readTime: 'Lesezeit',
  publishedAt: 'Datum'
};

export type CollectionRenderKey = `${IndustryKey}:${string}`;

/**
 * Every non-seo top-level `item.data` key must appear in frontend (cards, meta, facts, narrative blocks, gallery, video).
 * Keep in sync with SeedRenderer + preview-route collection detail builders.
 */
export const COLLECTION_RENDERED_DATA_ROOTS: Record<CollectionRenderKey, readonly string[]> = {
  'restaurant:menuItem': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'price',
    'ingredients',
    'allergens',
    'dietaryTags',
    'pairingRecommendation',
    'videoUrl',
    'cta'
  ],
  'restaurant:diningExperience': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'duration',
    'price',
    'capacity',
    'scheduleInfo',
    'included',
    'videoUrl',
    'cta'
  ],
  'restaurant:restaurantInsight': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'kicker',
    'metric',
    'detail',
    'cta'
  ],
  'restaurant:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'hotel:room': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'images',
    'sizeSqm',
    'occupancy',
    'bedType',
    'view',
    'priceFrom',
    'amenities',
    'videoUrl',
    'cta'
  ],
  'hotel:hotelOffer': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'travelPeriod',
    'priceFrom',
    'included',
    'videoUrl',
    'cta'
  ],
  'hotel:hotelInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'hotel:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'tourism:tour': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'duration',
    'distance',
    'elevationGain',
    'difficulty',
    'season',
    'price',
    'meetingPoint',
    'included',
    'requirements',
    'packingList',
    'videoUrl',
    'cta'
  ],
  'tourism:tourismInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'tourism:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'salon:treatment': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'duration',
    'priceFrom',
    'preparation',
    'aftercare',
    'videoUrl',
    'cta'
  ],
  'salon:look': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'images',
    'styleTags',
    'relatedServices',
    'videoUrl',
    'cta'
  ],
  'salon:salonInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'salon:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'tradesman:tradeService': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'problemStatement',
    'solutionSummary',
    'serviceArea',
    'videoUrl',
    'cta'
  ],
  'tradesman:referenceProject': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'images',
    'location',
    'projectType',
    'duration',
    'servicesIncluded',
    'customerQuote',
    'videoUrl',
    'cta'
  ],
  'tradesman:tradesmanInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'tradesman:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'consulting:consultingService': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'targetAudience',
    'problemTypes',
    'deliverables',
    'duration',
    'cta'
  ],
  'consulting:caseStudy': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'industry',
    'challenge',
    'approach',
    'results',
    'metrics',
    'testimonial',
    'videoUrl',
    'cta'
  ],
  'consulting:consultingInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'consulting:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'medical:treatment': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'indications',
    'procedure',
    'preparation',
    'aftercare',
    'coveredByInsurance',
    'duration',
    'videoUrl',
    'cta'
  ],
  'medical:doctor': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'role',
    'specialties',
    'bio',
    'languages',
    'consultationHours',
    'videoUrl',
    'cta'
  ],
  'medical:medicalInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'medical:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'fitness:fitnessClass': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'level',
    'duration',
    'schedule',
    'goals',
    'equipmentNeeded',
    'videoUrl',
    'cta'
  ],
  'fitness:trainer': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'role',
    'specialties',
    'bio',
    'certifications',
    'videoUrl',
    'cta'
  ],
  'fitness:fitnessInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'fitness:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ],
  'fitness:scheduleItem': ['title', 'slug', 'summary', 'image', 'weekday', 'time', 'level', 'trainer', 'duration', 'goals', 'videoUrl'],
  'wedding:scheduleItem': ['title', 'slug', 'summary', 'description', 'image', 'time', 'location', 'guestNote', 'videoUrl', 'cta'],
  'wedding:accommodation': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'location',
    'priceFrom',
    'distance',
    'bookingHint',
    'mapsUrl',
    'videoUrl',
    'cta'
  ],
  'wedding:weddingInsight': ['title', 'slug', 'summary', 'description', 'image', 'kicker', 'metric', 'detail', 'cta'],
  'wedding:newsArticle': [
    'title',
    'slug',
    'summary',
    'description',
    'image',
    'category',
    'publishedAt',
    'author',
    'readTime',
    'cta'
  ]
};

export function renderedCollectionDataRootSet(industry: IndustryKey, collectionKey: string): Set<string> {
  const key = `${industry}:${collectionKey}` as CollectionRenderKey;
  const list = COLLECTION_RENDERED_DATA_ROOTS[key];
  if (!list) {
    throw new Error(`COLLECTION_RENDERED_DATA_ROOTS missing entry for ${key}`);
  }
  return new Set(list);
}
